# Generated by Django 3.2 on 2021-05-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed', '0002_alter_register_ct_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='ct',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='oc',
            field=models.PositiveIntegerField(default=135),
        ),
        migrations.AlterField(
            model_name='register',
            name='oxy',
            field=models.PositiveIntegerField(),
        ),
    ]
