# Generated by Django 3.2 on 2021-05-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bed', '0005_alter_register_oc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='ct_pdf',
        ),
    ]
