# Generated by Django 3.2 on 2021-05-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed', '0009_auto_20210521_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
