# Generated by Django 3.2 on 2021-05-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed', '0003_auto_20210508_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='oc',
            field=models.PositiveIntegerField(),
        ),
    ]
