# Generated by Django 3.2 on 2021-05-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed', '0004_alter_register_oc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='oc',
            field=models.PositiveIntegerField(default=135),
        ),
    ]
