# Generated by Django 3.2 on 2021-05-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed', '0007_auto_20210521_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='p_id',
        ),
        migrations.AddField(
            model_name='register',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
